version: '2'

services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    expose:
      - "4444"
    environment:
      - GRID_TIMEOUT=0
# firefox:
#   image: selenium/node-firefox
#   environment:
#     - HUB_PORT_4444_TCP_ADDR=hub
#     - HUB_PORT_4444_TCP_PORT=4444
  chrome:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    volumes:
      - ..:/app
      - /app/node_modules
      - /dev/shm:/dev/shm
