FROM jenkins/jenkins:lts
USER root
  RUN apt-get update \
  && apt-get install -y sudo \
  && rm -rf /var/lib/apt/lists/*

RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

# drop back to the regular jenkins user - good practice
USER jenkins

